# Generated by Django 4.2.5 on 2023-12-28 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_menu_order_booking_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Userlogin',
        ),
    ]
