# Generated by Django 4.2.5 on 2024-01-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_rename_login_userlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logindetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('Date', models.DateTimeField()),
            ],
        ),
    ]
